import {
  CONSUMPTION_BAND_VALUES,
  CORE_REGION_CODES,
  ENERGY_RETAIL_COMPARISON_BASIS_VALUES,
  ENERGY_WINDOW_VALUES,
  HOUSING_OVERVIEW_REQUIRED_SERIES_IDS,
  NATIONAL_AND_STATE_REGION_CODES,
  TAX_STATUS_VALUES
} from "@aus-dash/data-contract";

export const API_SUPPORTED_REGIONS = new Set<string>(CORE_REGION_CODES);

export const ENERGY_RETAIL_SUPPORTED_REGIONS = new Set<string>(
  NATIONAL_AND_STATE_REGION_CODES
);

export const ENERGY_OVERVIEW_SUPPORTED_REGIONS = ENERGY_RETAIL_SUPPORTED_REGIONS;

const UNSUPPORTED_WHOLESALE_REGIONS = new Set(["WA", "NT", "ACT"]);
export const ENERGY_WHOLESALE_SUPPORTED_REGIONS = new Set<string>(
  NATIONAL_AND_STATE_REGION_CODES.filter(
    (code) => !UNSUPPORTED_WHOLESALE_REGIONS.has(code)
  )
);

export const ENERGY_SUPPORTED_WINDOWS = new Set<string>(ENERGY_WINDOW_VALUES);

export const ENERGY_RETAIL_COMPARISON_BASIS = new Set<string>(
  ENERGY_RETAIL_COMPARISON_BASIS_VALUES
);

export const ENERGY_RETAIL_TAX_STATUS = new Set<string>(TAX_STATUS_VALUES);

export const ENERGY_RETAIL_CONSUMPTION_BANDS = new Set<string>(
  CONSUMPTION_BAND_VALUES
);

export const REQUIRED_HOUSING_OVERVIEW_SERIES_IDS = [
  ...HOUSING_OVERVIEW_REQUIRED_SERIES_IDS
] as const;
